#!/usr/bin/env python3

import gi
gi.require_version("Playerctl", "2.0")

from gi.repository import Playerctl, GLib
import sys
import signal
import json

def on_metadata_changed(player, metadata, _=None):
  artist = player.get_artist()
  title = player.get_title()

  if artist == "" or title == "":
    sys.stdout.write("\n")
    sys.stdout.flush()
    return

  sys.stdout.write(f"{json.dumps({ "text": f"{artist} - {title}", "tooltip": f"{artist} - {title}" })}\n")
  sys.stdout.flush()

def on_player_vanished(manager, player):
  if player.props.player_name == "spotify":
    sys.stdout.write("\n")
    sys.stdout.flush()

def init_player(manager, name):
  if name.name != "spotify": return

  player = Playerctl.Player.new_from_name(name)
  player.connect("metadata", on_metadata_changed, None)
  manager.manage_player(player)
  on_metadata_changed(player, player.props.metadata)

def main():
  signal.signal(signal.SIGINT, lambda s, f: sys.exit(0))
  signal.signal(signal.SIGTERM, lambda s, f: sys.exit(0))
  signal.signal(signal.SIGPIPE, signal.SIG_DFL)

  manager = Playerctl.PlayerManager()
  manager.connect("name-appeared", init_player)
  manager.connect("player-vanished", on_player_vanished)

  for player in manager.props.player_names:
    init_player(manager, player)

  GLib.MainLoop().run()

if __name__ == "__main__":
  main()
