#!/bin/bash
set -euo pipefail

get_icon() {
  local lc=${1,,}

  case "$lc" in
    *thunder*|*storm*) printf ' ';;
    *sleet*) printf ' ';;
    *snow*) case "$lc" in *heavy*) printf ' ';; *) printf ' ';; esac;;
    *overcast*|*very*cloud*) printf ' ';;
    *fog*|*mist*|*haze*) printf ' ';;
    *heavy*rain*|*torrential*) printf ' ';;
    *rain*|*drizzle*|*shower*) printf ' ';;
    *partly*cloud*) printf ' ';;
    *cloud*) printf ' ';;
    *sunny*|*clear*) printf ' ';;
    *) ;;
  esac
}

result=$(weather -f "%t|%f|%l|%h|%C") || exit 1
[[ -z "$result" ]] && exit 1

printf '%s' "${result%|*}|$(get_icon "${result##*|}")" |\
  jq -Rrsc '
    def fix_temp:
      sub("\\+(?<r>[0-9]+)°C"; "\(.r)°C");

    split("|") |
    {text: "\(.[4])\(.[0] | fix_temp)",
     alt: "\(.[4])\(.[0] | fix_temp) (\(.[2]) \(.[1] | fix_temp)) \(.[3])",
     tooltip: "\(.[2]) (feels like \(.[1] | fix_temp)), humidity \(.[3])"}'
