(add-to-list 'load-path (concat user-emacs-directory "modules"))

(require 'packages)
(require 'variables)
(require 'options)
(require 'fonts)
(require 'functions)
(require 'keymaps)
(require 'tools)
(require 'prog-tools)
(require 'prog-exts)
(require 'term-conf)
