#!/bin/sh

BG_DIR="$HOME/.config/backgrounds"
METAFILE="$BG_DIR/.bgmeta"

function usage {
  echo "usage: $0 {next|refresh}"
}

function get_images {
  sed '/---/q' "$METAFILE"
}

function get_image_count {
  wc -l < <(get_images)
}

function refresh_meta {
  find "$BG_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | shuf > "$METAFILE"
  echo "---" >> "$METAFILE"
  echo "$((RANDOM % $(get_image_count)))" >> "$METAFILE"
}

function current_index {
  tail -n 1 "$METAFILE"
}

function get_current {
  mapfile -t images < <(get_images)
  echo "${images[$(current_index)]}"
}

function update_index {
  current=$(current_index)
  sed -i '$d' "$METAFILE"
  echo "$((($current + 1) % $(get_image_count)))" >> "$METAFILE"
}

function set_bg {
  feh --no-fehbg --bg-scale "$1"
}

function update_lockscreen_bg {
  betterlockscreen -u "$1" --fx blur
}

if [ ! -f "$METAFILE" ]; then refresh_meta; fi

case "$1" in
  refresh)
    refresh_meta;;
  next)
    image=$(get_current)
    update_index
    set_bg "$image"
    update_lockscreen_bg "$image";;
  *)
    usage
    exit 1;;
esac
