#!/bin/sh

BG_DIR="$HOME/.config/backgrounds"
METAFILE="$BG_DIR/.bgmeta"

usage() {
  echo "usage: $0 {next|refresh}"
}

get_images() {
  sed '/---/q' "$METAFILE"
}

get_image_count() {
  get_images | wc -l
}

refresh_meta() {
  find "$BG_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | shuf > "$METAFILE"
  echo "---" >> "$METAFILE"
  awk -v max="$(get_image_count)" 'BEGIN { srand(); print int(rand() * max) }' >> "$METAFILE"
}

current_index() {
  tail -n 1 "$METAFILE"
}

get_current() {
  get_images | sed -n "$(($(current_index) + 1))p"
}

update_index() {
  current=$(current_index)
  sed -i '$d' "$METAFILE"
  echo "$(((current + 1) % $(get_image_count)))" >> "$METAFILE"
}

set_bg() {
  feh --no-fehbg --bg-scale "$1"
}

update_lockscreen_bg() {
  betterlockscreen -u "$1" --fx blur
}

if [ ! -f "$METAFILE" ]; then refresh_meta; fi

case "$1" in
  refresh)
    refresh_meta;;
  next)
    image=$(get_current)
    update_index
    set_bg "$image"
    update_lockscreen_bg "$image";;
  *)
    usage
    exit 1;;
esac
