#!/bin/sh

case "$1" in
  "dim")
    if ! pgrep -f betterlockscreen > /dev/null; then
      xrandr --output "DP-0" --brightness .1
    fi;;
  "undim")
    xrandr --output "DP-0" --brightness 1;;
  *)
    echo "usage: $0 {dim|undim}"
    exit 1;;
esac
