#!/bin/sh

if ! pgrep -f xidlehook > /dev/null; then
  xidlehook \
    --not-when-fullscreen \
    --not-when-audio \
    --detect-sleep \
    --timer 300 \
    "$HOME/.config/i3/scripts/dim-screen dim" \
    "$HOME/.config/i3/scripts/dim-screen undim" \
    --timer 1500 \
    "$HOME/.config/i3/scripts/dim-screen undim; $HOME/.config/i3/scripts/lock-screen" \
    ''
else
  echo "idle: $(xidlehook --print)"
fi
