#!/bin/sh

in_group() {
  hyprctl activewindow -j |\
    jq '((.grouped // []) | length) > 0' |\
    rg -q true
}

move() {
  direction="$1"

  if in_group; then
    case "$direction" in
      l) direction="b";;
      r) direction="f";;
      *) exit 1;;
    esac

    hyprctl -q dispatch changegroupactive "$direction"
  else
    hyprctl -q dispatch movefocus "$1"
  fi
}

move "$1"
